FROM ubuntu:latest

WORKDIR /app

ADD /../../frontend ./frontend
ADD /../../requirements.txt .

RUN apt-get update && apt-get install python3-pip -y && apt-get -y install libpq-dev gcc  && pip install -r requirements.txt 

WORKDIR /app/frontend


CMD streamlit run TotalCasesandDeaths.py





