version: "3.9"

services:
 
  db:
    image: bdd:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
 
